on:
  push:
    tags:
    - 'v*'

name: Release CI

jobs:
  build:
    name: Upload release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Setup Java
        uses: actions/setup-java@v3.6.0
        with:
          java-version: 8
          distribution: temurin
      - name: Set SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Add known host key
        run: ssh-keyscan javacard.pro >> ~/.ssh/known_hosts
      - name: Package
        run: ./mvnw -T1C -U -B verify && ant
      - name: Release
        id: create_release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: |
            ant-javacard.jar
          fail_on_unmatched_files: true
          body: Release ${{ github.ref_name }}
          prerelease: true # manually promoted

      - name: Deploy package
        run: ./mvnw -B deploy
